start:
	cd ../VirtualEnviroment/bin
	activate
	python manage.py runserver 

runserver:
	python manage.py runserver

migrations:
	python manage.py makemigrations
	python manage.py migrate
	python manage.py runserver
